# File: .github/workflows/workflow.yml

on:
  push:
    branches: 
    - master

name: AKS_CD_script

jobs:
  Azure-CD-test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@master
      - name: GetVersion
        run: |
          version=`cat .VERSION`
          echo ${version}
