on: push

name: test-env-management-workflow

jobs:
  Build-test-env:
    runs-on: ubuntu-latest 
    # github.head_ref is source branch
    # the branch name ended with the flag '/bte' will trigger follow steps
    # bte means 'build test environment'
#    if: ${{endsWith(github.head_ref, '/bte') && github.event.action != 'closed' }} 
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
    
    #- name: get env
    #  run: |
    #    env
    #    cat /home/runner/_work/_temp/_github_workflow/event.json

    - name: Get branch information
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=branch::$(echo $GITHUB_HEAD_REF|sed 's/\//_/g'|tr [:upper:] [:lower:])"
      id: vars
          
    - name: show secrets
      run: |
        set -x
        port=${{ secrets.POSTGRES_PORT }}
        echo $port


