on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

name: Build-test-env

jobs:
  Build-test-env:
    runs-on: [self-hosted, linux, x64]
    # github.head_ref is source branch
    #if: ${{endsWith(github.head_ref, '/bte')}} 
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
    
    - name: get env
      run: |
        env
        cat /home/runner/_work/_temp/_github_workflow/event.json

    - name: Get branch information
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=branch::$(echo $GITHUB_HEAD_REF|sed 's/\//_/g'|tr [:upper:] [:lower:])"
      id: vars
          
    - name: ls
      run: |
        ls -al