on:
  push:
    branches: 
    - master

name: build-test

jobs:
  Build-stage:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
      
    - run: |
        ls -al
          
    - name: DockerLogin
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: DockerBuild
      env:
        v: ${{ env.v }}
      run: |
        v=`cat k8s/.VERSION`
        echo ${v}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/test:${v} -f k8s/test-dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/test:${v}
