on:
  push:
    tags:
      - 'build-test-env'

name: build-test

jobs:
  Build-stage:
    runs-on: my-runner
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
      
    - run: |
        ls -al
          
    - name: DockerLogin
      run: docker login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PWD }} ${{ secrets.HARBOR_ADDR }}
    - name: DockerBuild
      run: |
        
        git_branch=
        docker build -t ${{ secrets.HARBOR_ADDR }}/ciddtest/${branch#refs/heads/}:${GITHUB_SHA} -f k8s/test-dockerfile .
        docker push ${{ secrets.HARBOR_ADDR }}/ciddtest/${branch#refs/heads/}:${GITHUB_SHA}
