on:
  push:
    branches: 
    - master

name: build-test

jobs:
  Build-stage:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
      
    - run: |
        ls -al
    
    - name: GetVersion
      env:
        v: ${{env.v}}
      run: |
        v=`cat k8s/.VERSION`
        echo ${v}
        env
          
    - name: BuildImages
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: blockchen1020/test
        tag: ${{INPUT_V}}
        registry: docker.io
        dockerfile: k8s/test-dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    
