on:
  push:
    branches: 
    - master

name: build-test

jobs:
  Build-stage:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
      
    - run: |
        ls -al
    
    - name: GetVersion
      env:
        v: ${{env.v}}
      run: |
        v=`cat k8s/.VERSION`
        echo ${v}
        env
          
    - name: DockerLogin
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: DockerBuild
      run: docker build -t ${{ secrets.DOCKER_USER }}/test:${{env.v}} .
    - name: DockerPush
      run: docker push ${{ secrets.DOCKER_USER }}/test:${{env.v}}
