on: push

name: test-env-management-workflow

env:
  HELM_CHART_PATH=k8s/helm/test-seasalt
  INSTALL_POSTGRES=true
  PULLSECRET=harbor-pull-secret
  LOGIN_FROM_DECKERCONF_ENABLE=true


jobs:
  Build-test-env:
    runs-on: ubuntu-latest 
    # github.head_ref is source branch
    # the branch name ended with the flag '/bte' will trigger follow steps
    # bte means 'build test environment'
#    if: ${{endsWith(github.head_ref, '/bte') && github.event.action != 'closed' }} 
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
    
    #- name: get env
    #  run: |
    #    env
    #    cat /home/runner/_work/_temp/_github_workflow/event.json

    - name: Get branch information
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=branch::$(echo $GITHUB_HEAD_REF|sed 's/\//_/g'|tr [:upper:] [:lower:])"
      id: vars
          
#    - name: show secrets
#      run: |
#        set -x
#        port=${{ secrets.POSTGRES_PORT }}
#        echo $port

    - name: test env
      run: |
        echo $HELM_CHART_PATH
        echo $INSTALL_POSTGRES
        echo $PULLSECRET
        echo $LOGIN_FROM_DECKERCONF_ENABLE
