on:
  push:
    branch:
      - '*-build-test-env'

name: build-test

jobs:
  Build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master
      
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
          
    - name: DockerLogin
      run: docker login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PWD }} https://harbor.seasalt.ai
    - name: DockerBuild
      run: |
        docker build -t harbor.seasalt.ai/ciddtest/${{ steps.extract_branch.outputs.branch }}:${{GITHUB_SHA}} -f k8s/test-dockerfile .
        docker push harbor.seasalt.ai/ciddtest/${{ steps.extract_branch.outputs.branch }}:${{GITHUB_SHA}}
