name: Lint with 

on: [push]

jobs:
  scan:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master     
    - run: |
        ls -al
        pwd

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

  cache:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

  wrong:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name : Wrong
      run: |
        python hello_world.py
    continue-on-error: true

  Do:
    runs-on: [self-hosted, linux, x64]
    continue-on-error: true
    steps:
    - name: echo
      run: |
        echo pass
