name: Lint with 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master     
    - run: |
        ls -al
        pwd

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install step
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        pip install --user -r requirements.txt 

    - name: show local pip
      run: |
        ls -al /home/runner/.cache/pip
        python -c "import sys; print(sys.executable)"
        echo $RUNNER_TOOL_CACHE
        ls -al $RUNNER_TOOL_CACHE/Python/3.6.11
        ls -al $RUNNER_TOOL_CACHE/PyPy

    - name: Run python
      run: |
        export PYTHONPATH=/home/runner/.cache/pip
        export PATH=/home/runner/.local/bin:$PATH
        python tests/test_fake.py

    - name: Lint with flake8
      run: |
        export PYTHONPATH=/home/runner/.cache/pip
        export PATH=/home/runner/.local/bin:$PATH
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        export PYTHONPATH=/home/runner/.cache/pip
        export PATH=/home/runner/.local/bin:$PATH
        pytest -v

    - name: Check typing with pytype
      run: |
        export PYTHONPATH=/home/runner/.cache/pip
        export PATH=/home/runner/.local/bin:$PATH
        pytype -P /home/runner/work/myrepo/myrepo/tests input /home/runner/work/myrepo/myrepo/tests
