name: Lint with 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepo
      uses: actions/checkout@master     
    - run: |
        ls -al
        pwd

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install step
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt --install-option="--prefix=/home/runner/.cache/pip"

    - name: show cache
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        ls -al /home/runner/.cache/pip

    - name: Run python
      run: |
        export PYTHONPATH=/home/runner/.cache/pip
        python tests/test_fake.py

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v

    - name: Check typing with pytype
      run: |
        pytype -P /home/runner/work/myrepo/myrepo/tests input /home/runner/work/myrepo/myrepo/tests
